### ISSUE TITLE
Add Unified Astronomy Thesaurus Autocomplete Widget for DOI Keywords

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-ui#11]
Autocomplete widget is here: http://astrothesaurus.org/thesaurus/autocomplete-widget/ 

Right now, DOI Service provides some basic subset of keywords, but using the UAT is probably a better method for ensuring we use a more consistent vocabulary across DOIs.

I imagine we would want to allow the autocomplete, but also allow for custom keywords, we can then, eventually, go back through these custom keywords and look to submit those back to UAT.

If the implementation is not straightfoward, we may want to punt this. But I imagine if we don't do this now, we never will...

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo In the following form can you add the widget described above.

<img width="1035" alt="Screen Shot 2021-01-04 at 9 47 24 AM" src="https://user-images.githubusercontent.com/60993872/103563737-26418b00-4e72-11eb-9d67-70a801dcd46e.png">

Below the document input text, we will have the widget with description: "add keyword from astrothesaurus:"

The action will add the keywords in the xml in the keyword tag.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo started to work on it, will be part of the next pull request

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo had some complication due to synchronization of fields but this will be solved soon.
