### ISSUE TITLE
After reserve one file successfully, resubmit a new file

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#22]
I was not able to come back to the reserve submission steps from the attached screen.

<img width="1116" alt="Screen Shot 2021-02-09 at 1 28 34 PM" src="https://user-images.githubusercontent.com/60993872/107431045-c6767980-6ada-11eb-9c66-0134add246cb.png">

**Comment by eddiesarevalo** [comment]
Currently it stays stuck on this screen unless click _home_ then _create doi_ again.
![Screen Shot 2021-06-22 at 10.13.54 AM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/25b3f876-b56f-4363-a5f5-a168d144d538)

Will add a button that says _Create another DOI_ that will reset the form.
