### ISSUE TITLE
As a user, I want to search for a DOI and associated metadata by LID/LIDVID

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#25]
...so i can use the DOI in a citation or trace back from a DOI to an associated bundle, collection, or product LID/LIDVID

## Details
Web page that displays all available DOIs in the PDS.

NOTE: As much as possible, let's try to replicate the search functionality implemented in the DOI UI.

### Initial State
This page should appear as the landing page for the DOI UI. From this page, it should display a table of all PDS DOIs, ordered by latest update date.

![Screen Shot 2021-03-22 at 5.40.23 PM.png](https://images.zenhubusercontent.com/5c87e6cfd74bd07972c707d3/62ac1fba-f3f8-4a31-9b8c-439f16760c97)

### Search
Here is a quick wireframe of what I am thinking about the UI layout. This will go at https://pds.nasa.gov/datastandards/citing/doi .

![Screen Shot 2021-03-22 at 5.41.38 PM.png](https://images.zenhubusercontent.com/5c87e6cfd74bd07972c707d3/43f918c4-4318-48cd-afb0-f49493be12e4)

Additionally, it should provide a basic search capability where a user can:
1. (this ticket) enter a LID/LIDVID and get the results associated DOI metadata
2. (see #33) enter a DOI and get the resulting associated DOI metadata

 The LID or LIDVID can come in several forms:
* bundle LID / LIDVID - `urn:nasa:pds:<bundle_id>`
* collection LID / LIDVID  - `urn:nasa:pds:<bundle_id>:<collection_id>`
* product LID / LIDVID (for documents) - `urn:nasa:pds:<bundle_id>:<collection_id>:<product_id>`
* LIDVID - `LID::<version_id>

See DOI UI for how this is being handled over there for querying the the service.

Here is some logic for what I think needs to happen for the search:

For primary results at the top
```
if search by DOI / LID/ LIDVID not found:
    display "Exact match not found", and move onto related DOI section
```

For related DOI metadata (should include related DOIs even if an exact match is found):
```
if search by product LID / LIDVID `urn:nasa:pds:<bundle_id>:<collection_id>:<product_id>` not found:
    search for the parent collection DOI by removing the `<product_id>` from the LID/LIDVID: `urn:nasa:pds:<bundle_id>:<collection_id>`

if search by collection LID / LIDVID `urn:nasa:pds:<bundle_id>:<collection_id>` not found:
    search for the parent bundle DOI by removing the `<collection_id>` from the LID/LIDVID: `urn:nasa:pds:<bundle_id>`

if search by bundle LID / LIDVID not found: # currently wildcards are unsupported by API
    search for all child collections with `urn:nasa:pds:<bundle_id>:*` 
```

## Technical Info

How to connect to the validation API:

```
ssh -L 8085:localhost:8080 pds-dev3
```

See http://localhost:8085/PDS_APIs/pds_doi_api/0.1/ui/

**Comment by jordanpadams** [comment]
some search capability would also be great, but not necessarily required. we need to support searches by:
* bundle LID / LIDVID
* collection LID / LIDVID 
* product LID / LIDVID (for documents)

in all cases, if a LID/LIDVID is an exact match in the DOI database, that should be the first result. we should then have "related DOIs" by searching for all DOIs for that particular bundle, e.g. if someone searches for ``urn:nasa:pds:insight_cameras` (bundle) or `urn:nasa:pds:insight_cameras:document` (collection) or `urn:nasa:pds:insight_cameras:document:foobar.pdf` (product), we search the database at the bundle level `urn:nasa:pds:<bundle_LID>*` == ``urn:nasa:pds:insight_cameras*`

**Comment by tloubrieu-jpl** [comment]
ssh -L 8085:localhost:8080 pds-dev3

http://localhost:8085/

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl need to check if the UI and API can be used with LID only criteria

**Comment by jordanpadams** [comment]
@c-suh I've updated the ticket with more details. let me know if you have any more questions.

@tloubrieu-jpl take a look and let me know if there is anything else you can think of.

**Comment by jordanpadams** [comment]
@c-suh i think we are ready to start working on this. take a look at the wireframes and some of the info provided and let's chat if there are some issues you are looking to address. the wireframes are very clunky but hopefully give you an idea what we are looking for.

**Comment by tloubrieu-jpl** [comment]
@c-suh will go-on with it today and go on tomorrow.

**Comment by tloubrieu-jpl** [comment]
@c-suh for the related doi cases, on pds-dev3 you can use:

Case 1:
lid=urn:nasa:pds:insight_cameras:calibration:product_x

should return as related doi:
collection: urn:nasa:pds:insight_cameras:calibration

Case 2:
search for lid: urn:nasa:pds:lab_shocked_feldspars:calibrated:product_z

should return ,as related doi:
collection: urn:nasa:pds:lab_shocked_feldspars:calibrated
bundle: urn:nasa:pds:lab_shocked_feldspars

Case 3.
search for collection lid: collection urn:nasa:pds:lab_shocked_feldspars_21:calibrated
shoud return:
   as exact match: the collection urn:nasa:pds:lab_shocked_feldspars_21:calibrated
   as related doi: the bundle urn:nasa:pds:lab_shocked_feldspars_21

Question for @jordanpadams, how would that make sense to manage versions (vid) here ? Should we ignore them in the search criteria for now ?
