### ISSUE TITLE
Develop Web UI for DOI service

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#3]
provide a web UI for the doi service so that eventually a user in a discipline node can submit a doi on its own with less manual contribution from Engineering Node operator.

**Comment by jordanpadams** [comment]
📆  November Status: ticket moved from doi-service repo. on track

**Comment by jordanpadams** [comment]
📆 December Status: delayed due to increased scope. planned for January completion. no impact on other tasks.

**Comment by jordanpadams** [comment]
:calendar: january status: delayed due to unexpected scope increase not planned for at beginning of build. no foreseeable impact on B11.1 delivery.

**Comment by jordanpadams** [comment]
📆 february status: finalizing implementation for initial deployment. on schedule for B11.1 I&T
