### ISSUE TITLE
On release screen, have only one "ignore warning" checkbox

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#31]
The same value can be used for both "save" and "release"

**Comment by c-suh** [comment]
@tloubrieu-jpl can you attach a screenshot? I haven't come across any "ignore warning" checkboxes

**Comment by tloubrieu-jpl** [comment]
Sorry, here some details:
You should:
1. click on release
2. select one DOI or LIDVID, for example `urn:nasa:pds:lab_shocked_feldspars_3::3.0`
3. you should see the screenshot

![image](https://user-images.githubusercontent.com/60993872/111382944-d1d23d00-8664-11eb-94dc-35ea302f5f3e.png)

**Comment by c-suh** [comment]
![Screen Shot 2021-03-16 at 2 45 16 PM](https://user-images.githubusercontent.com/18314609/111384161-6a1cf180-8666-11eb-83db-b3891dc3b288.png)

I also searched the code for any checkbox-like elements but came up empty. I will pull the latest code and try again. Thank you for the screenshot!

**Comment by tloubrieu-jpl** [comment]
Cool!

**Comment by c-suh** [comment]
![Screen Shot 2021-03-17 at 11 59 45 AM](https://user-images.githubusercontent.com/18314609/111523252-4ca86000-8718-11eb-9281-7a33c9a31998.png)

@tloubrieu-jpl let me know if you would like it placed differently

**Comment by tloubrieu-jpl** [comment]
@c-suh good point, i don't have a huge expertise in that domain but I also felt that this can be improved. I think save and release button can be on the same line. Keep them centered for now, so that it is consistent with the reserve layout. But honestly, whatever you think is good will work for me.

**Comment by c-suh** [comment]
@tloubrieu-jpl apologies, to clarify: since I am temporarily filling in for Eddie, I'm hesitant to change the style too much from what he has implemented, but if there is a strong preference for the upcoming demonstration, I will make the changes.
