### ISSUE TITLE
As a user, I want to acquire a DOI for a PDS4 product that has been registered and is publicly accessible

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-ui#42]
## Motivation
...so that I can get a DOI for a PDS4 product after it has already been publicly released. 

The [PDS Policy](https://pds.nasa.gov/datastandards/documents/policy/PolicyOnDOI10142020.pdf) describes that the PDS "should" acquire DOIs prior to peer review. However, some scenarios will call for DOIs after the fact (e.g. DOIs for already existing User Guides or other documentation where a DOI was not foreseen as being needed prior to peer review).

## Acceptance Criteria
**Given** an PDS4 product that has been registered, a landing page exists, and the data is available publicly online
**When I perform** a request to get a new DOI
**Then I expect** to be prompted to "release a new DOI"
**Then I expect** to be prompted to input the expected metadata to release a DOI
**Then I expect** to submit the required metadata to the DOI service
**Then I expect** to receive a notification as to the status of the request
**Then I expect** a DOI to be displayed, or information on how I will receive that DOI
**Then I expect** the information I entered to be saved in a draft state until it is released

**Given** an PDS4 product that has not been registered, a landing page does not exist, or the data is not publicly accessible
**When I perform** a request to get a DOI
**Then I expect** to be prompted to "release a new DOI"
**Then I expect** to be prompted to input the expected metadata to release a DOI
**Then I expect** to submit the required metadata to the DOI service
**Then I expect** to receive a prompt that the DOI request has failed do to the lack of landing page / public accessibility of the data.
**Then I expect** the information I entered to be saved in a draft state until it is released

### Related Requirements
🦄 https://github.com/NASA-PDS/pds-doi-service/issues/7

**Comment by jordanpadams** [comment]
closed per https://app.zenhub.com/workspace/o/nasa-pds/pds-doi-ui/issues/51

**Comment by gxtchen** [comment]
@tloubrieu-jpl @jordanpadams I need access to the doi service and doi ui in pds-gamma.
