### ISSUE TITLE
Develop mock-ups for DOI Service Landing Page and Create Page

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-ui#44]

**Comment by edwardbarraza** [comment]
Made some mockups for our first iteration

https://www.figma.com/proto/D7n5ODxbsHu3DDxE3ykIUV/DOI?page-id=1472%3A312&node-id=1511%3A78&viewport=-11961%2C-2956%2C0.9933163523674011&scaling=contain

**Comment by edwardbarraza** [comment]
I've made some updates, incorporating feedback I received this week. Updates are to the Review/Release pages:

https://www.figma.com/proto/D7n5ODxbsHu3DDxE3ykIUV/DOI?page-id=1472%3A312&node-id=1511%3A78&viewport=-2889%2C-74%2C0.21843890845775604&scaling=min-zoom
