### ISSUE TITLE
Enhancements per initial implementation of mockups

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-ui#48]
Here some updates to be implemented to the initial dev completed for #44 

- [x] Change “Get URL” to “Upload Label”
- [x] Add "Upload Label" button next to text box
- [x] "Save" and "Submit for Review" buttons side-by-side
- [x] Add DOI(s) returned from Reserve step to output message
- [x] Update API requests per latest changes to https://miro.com/app/board/o9J_lF_ReJo=/
    - [x] `Save` button -> `POST /dois with action=draft`
    - [x] `Submit for Review` button -> `POST /dois with action=draft` AND `POST /dois/{lidvid}/submit to submit for review`
- [x] Update "Nodes" dropdown to be "Node" (the dropdown contains all the nodes, but the user is inputting their Node)

**Comment by c-suh** [comment]
@jordanpadams, I addressed a few of these items in my most recent push to branch issue-44:
- Add DOI(s) returned from Reserve step to output message
- Update API requests per latest changes to https://miro.com/app/board/o9J_lF_ReJo=/
   - Save button -> POST /dois with action=draft
   - Submit for Review button -> POST /dois with action=draft AND POST /dois/{lidvid}/submit to submit for review

1. For the first bullet point, however, please note that the link will not work until we have URL handling implemented for the different "pages". I imagine that you would also like to change the wording/presentation of the information in the green box:
![Screen Shot 2021-05-26 at 6 19 45 PM](https://user-images.githubusercontent.com/18314609/119750914-12151f00-be4f-11eb-8470-38bf03fabd06.png)

2. For the second and third items in the [main description above](https://github.com/NASA-PDS/pds-doi-ui/issues/48#issue-903084439), how does this affect the placement of the "Ignore warnings" checkbox?

**Comment by jordanpadams** [comment]
@c-suh

> For the first bullet point, however, please note that the link will not work until we have URL handling implemented for the different "pages". I imagine that you would also like to change the wording/presentation of the information in the green box:

This looks good to me.

> For the second and third items in the main description above, how does this affect the placement of the "Ignore warnings" checkbox?

I think we can leave it as-is for now below the Upload button (or we can move it to the right?). I'm still now sure how we want to handle that checkbox and when that should appear, so that may change down the road anyways.

**Comment by jordanpadams** [comment]
@c-suh FYI, updated a couple things in the original description, and move the help stuff to a separate ticket we will try to tackle later on
