### ISSUE TITLE
Update Release and Update DOI pages to follow similar design as Create DOI page

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-ui#54]
# Release DOI

**When I click on the release button for urn:nasa:pds:insight_hp3_tem:**

<img width="1247" alt="Screen Shot 2021-06-02 at 10 19 57 AM" src="https://user-images.githubusercontent.com/33492486/120524610-18922200-c38c-11eb-958c-72029afd25d2.png">

**what I would like to see is something that looks very similar to the create DOI page.**

<img width="1124" alt="Screen Shot 2021-06-02 at 10 27 42 AM" src="https://user-images.githubusercontent.com/33492486/120529400-5180c580-c391-11eb-9953-2ce1fa4bb206.png">

**If they select `Yes`:**

<img width="1122" alt="Screen Shot 2021-06-02 at 10 21 59 AM" src="https://user-images.githubusercontent.com/33492486/120529409-547bb600-c391-11eb-98e3-fda10cf1facb.png">

**If they select `No`, display the following text in a red error box:**
> The data must registered with PDS Engineering Node and made publicly available prior to the release of the DOI. See [FAQs](https://github.com/NASA-PDS/pds-doi-service/blob/master/docs/support/faqs.md) for more information.

---

# Update DOI

Same interface as `Release DOI`.

**Comment by jordanpadams** [comment]
@c-suh we can talk about this some more. obviously not robust UI designs, but hopefully close enough to show the expected content / workflow.

**Comment by c-suh** [comment]
Merged into `main` with PR https://github.com/NASA-PDS/pds-doi-ui/pull/66
