### ISSUE TITLE
unable to release a doi created with command line in doi-ui

### ISSUE THREAD

**Issue by gxtchen** [NASA-PDS/pds-doi-ui#55]
## 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/4574373/120549752-d3301d80-c3a8-11eb-9260-d03ef0c911d1.png)

## 📜 To Reproduce
1. pds-doi-cmd reserve -n eng -i doi5.csv -s "gxchen@jpl.nasa.gov"
2. pds-doi-cmd draft -n eng -i doi5.bundle.xml -s "gxchen@jpl.nasa.gov" > doi5.draft.xml
3. add doi id from step 1 to doi5.draft.xml
4. pds-doi-cmd release -n eng -i doi5.draft.xml -s "gxchen@jpl.nasa.gov" > doi5.release.xml

## 🕵️ Expected behavior
should be able to click on release button on the doi-ui's search result page, and the release page should show up correctly.

## 🖥 System Info

---

** :unicorn: Applicable requirements**

**Comment by jordanpadams** [comment]
@gxtchen can you provide us with the csv and XMLs you are using via the command-line?

@tloubrieu-jpl should we table testing the DOI UI since we are currently significantly updating this? we can do testing of this app after I&T?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I am preparing a new stable release for @gxtchen so he could start to test it, but we could also table that for later.

I updated the deployment procedure in the README and created a release https://github.com/NASA-PDS/pds-doi-ui/releases/tag/v0.3.0

@gxtchen dropped the test files in there (we did the ticket together), but I don't see them. @gxtchen can you redrop the files in the bug description or in a comment ?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl sounds good. i think the changes that Catherine has implemented should suffice for I&T. the other things we mentioned are most nitpicks regarding the UI layout

@gxtchen as a note, you will have to rename those files with `.txt` or zip them up in order to attach them.

**Comment by jordanpadams** [comment]
closing as wontfix. this was with older implementation of DOI UI

**Comment by tloubrieu-jpl** [comment]
@jordanpadams would that be worth asking @gxtchen to retest it ? I though this bug might still be valid for the new UI version since we did not test submitting a DOI with the command line and updating it in the UI (as in this bug). 

However this is an edge case, so if it is not a priority I am ok to leave it closed.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl sure. maybe shoot @gxtchen an email in case he does not see this.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl as a note, we will need to create a new build of this since the previous version you sent @gxtchen did not work
