### ISSUE TITLE
DOI Search Component

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-ui#60]
REsearch on how to start that new component.

**Comment by tloubrieu-jpl** [comment]
What we are thinking of:
 - one repo with the common React components used for search (search input and results table) 
 - one repo for the doi-ui for edition and search
 - one repo for the search ui

**Comment by eddiesarevalo** [comment]
I think we should use a custom tool chain to build embeddable scripts and NPM publishable files. 
[https://app.zenhub.com/files/296461390/593c1ca9-cdee-41d8-bfad-c3b1f9e40438/download](https://app.zenhub.com/files/296461390/593c1ca9-cdee-41d8-bfad-c3b1f9e40438/download)

**Comment by jordanpadams** [comment]
📆 July Status: Completion will be delayed by at least 1 sprint as the search capability will require some refactoring

**Comment by jordanpadams** [comment]
:clock1: Deferring to B12.1 due to issues with DOI Service transition. No impact on B12.0

**Comment by jordanpadams** [comment]
Initial search capability completed. Breaking up of components and deployment are deferred to B12.1. Not a blocker for B12.0
