### ISSUE TITLE
As an administrator, I want to deploy the ui from a release and be able to change the back-end API urls

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#63]
## Motivation
...so that I can actually use the release package

## Additional Details

The js files are minified and it is not easily editable.

## Acceptance Criteria
**Given** a release package, e.g. https://github.com/NASA-PDS/pds-doi-ui/releases/tag/v0.3.0 
**When I perform** the deployment procedure, see https://github.com/NASA-PDS/pds-doi-ui/releases/tag/v0.3.0
**Then I expect** to be able to edit a configuration file where I can set the back-end API url in a single string

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @eddiesarevalo The ticket does not need to be urgently processed since the deployment procedure will work by using git clone before this ticket is solved

**Comment by tloubrieu-jpl** [comment]
Note @eddiesarevalo that would also help to have a single string to update in the configuration, since now Config.js is:
const Config = {
    api:{
        reserveUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois',
        getDoiByLidvidUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois/',
        getDoiByDoiUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois',
        getDoiByPds4LabelUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois',
        releaseDoiUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois/',
        baseUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois/'
    }
}

which is a lot a redundant string. Coud you also update that as part of this ticket ?

Thanks,

Thomas

**Comment by jordanpadams** [comment]
@eddiesarevalo think we can squeeze this into the work you are already doing?

**Comment by eddiesarevalo** [comment]
> Note @eddiesarevalo that would also help to have a single string to update in the configuration, since now Config.js is: const Config = { api:{ reserveUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois', getDoiByLidvidUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois/', getDoiByDoiUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois', getDoiByPds4LabelUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois', releaseDoiUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois/', baseUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois/' } }
> 
> which is a lot a redundant string. Coud you also update that as part of this ticket ?
> 
> Thanks,
> 
> Thomas

These two are different. I'm not sure if they will change in the future:
getDoiByIdentifier: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.2/doi',
releaseDoiUrl: 'http://localhost:8085/PDS_APIs/pds_doi_api/0.2/doi/',

**Comment by tloubrieu-jpl** [comment]
Hi @eddiesarevalo ,

I don't think we should have different configuration.

The difference is getDoiByIdentifier is followed by `?parameter=value...` and releaseDoiUrl is followed by '/<action>'

but the base url should be the same. Does that work ?
