### ISSUE TITLE
Remove dead comment code from SearchResults.jsx

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#69]
## 🐛 Describe the bug

There's a chunk of code in SearchResults.jsx (lines 187-279) which is mostly comments. Either the commented out part can be deleted or those lines can be replaced with null.

**Comment by jordanpadams** [comment]
This has been refactored pretty heavily over the past few weeks, so closing this as won't fix for the time being. Can re-open if needed
