### ISSUE TITLE
navigation issue when using the app bar

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#70]
## 🐛 Describe the bug
The browser's back button does not work after going to a discipline node site. 

## 📜 To Reproduce
See video

https://user-images.githubusercontent.com/60993872/125493563-20a9b23d-6b28-489f-bd57-99c44425c2c7.mov

## 🕵️ Expected behavior

The doi ui page should work or display a specific error message with redirection to a working page.

## 📚 Version of Software Used

branch routing_fixes

## 🖥 System Info

---

** :unicorn: Applicable requirements**

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl This is caused by the solution #64 This is a bug. I'll install an Apache server and debug. Thanks for the video! Let me know how you recorded that in the next meeting!

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo  the video is shit-command-5 on macos.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl I think you meant `shift` in your comment above 🤣

**Comment by tloubrieu-jpl** [comment]
> @tloubrieu-jpl I think you meant `shift` in your comment above 🤣

yes, you're right, i did not mean to be vulgar
