### ISSUE TITLE
As a user, I want to have a dedicated favicon for the service

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#71]
## Motivation
...so that I identify the application in my tabs.

## Additional Details

Currently the favicon is the default react icon.

The icon to be used need to be identified (pds ?).

## Acceptance Criteria
**Given** a DOI UI service deployment
**When I perform** a request on it in the browser
**Then I expect** to see an dedicated icon in my browser tab

**Comment by c-suh** [comment]
Use NASA meatball.
