### ISSUE TITLE
As a user, I want to see PDS3 id as they originally are

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#77]
## Motivation
...so that I can recognize my ids

## Acceptance Criteria
**Given** a service where doi history has been loaded
**When I perform** search on *BISTATIC*
**Then I expect** to see the research result with Ids containing /

## Engineering Details

So that it works, the UI need to use an alternate Id fields which is going to be provided by the ticket https://github.com/NASA-PDS/pds-doi-service/issues/229

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @collinss-jpl @c-suh @eddiesarevalo can this ticket be closed ?
I think Scott made the change on API side, I am guessing the change on UI side where done in a different ticket ?

**Comment by jordanpadams** [comment]
Let's close it for the RDD purposes, and reopen if it turns out this is not the case.
