### ISSUE TITLE
Document the security requirements for operational installation of the DOI UI

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-ui#8]
The UI form for release when the button release is clicked will do:

- call the API /dois/<lidvid>/submit
- an information message will say: "Your DOI has been submitted to Engineering Node. You will be notified if the DOI can be released or if updates are required."

The end point /dois/<lidvid>/release will never be called by the UI

**Comment by tloubrieu-jpl** [comment]
A new ticket is created for the development of the new form requirements.
