### ISSUE TITLE
Deploy DOI Search capability to pds-gamma

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-ui#84]
May be duplicate...

**Comment by eddiesarevalo** [comment]
Created a javascript embeddable widget version of the DOI search in pds-wds-react https://github.com/NASA-PDS/pds-wds-react/tree/embed-and-npm-builder. 

Demo at: https://pds-gamma.jpl.nasa.gov/tools/doi/

_Originally posted by @eddiesarevalo in https://github.com/NASA-PDS/pds-doi-ui/issues/61#issuecomment-929701116_
