### ISSUE TITLE
pds-doi-ui does not communicate to doi-service via port 8080

### ISSUE THREAD

**Issue by gxtchen** [NASA-PDS/pds-doi-ui#93]
## 🐛 Describe the bug identified during I&T
document pages for confiscating pds-doi-service uses port 8080 as the default port. But pds-doi-ui use 8085 to communicate to the api server. There are no message to the doi-ui user that the port 8085 couldn't be reached unless opening the inspection tools. The use can only change the setting in pds_doi_service.ini, but no where in pds-doi-ui.
We should change the document page in pds-doi-service to use 8085. 

## 🔁 : Related issues

---

### 🖥 System Info

---

**Comment by jordanpadams** [comment]
@tloubrieu-jpl can you take a look at this?

@gxtchen are you saying that the documentation needs updating or you are unable to connect the DOI UI to the DOI service because of a port issue?

**Comment by tloubrieu-jpl** [comment]
This ticket has been solved by pds-doi-ui#63
