### ISSUE TITLE
Status Findable does not have actions or links in the UI

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-ui#94]
## 🐛 Describe the bug

See screenshot from pds-gamma: https://pds-gamma.jpl.nasa.gov/dois/#/search/*

![image](https://user-images.githubusercontent.com/60993872/137958985-20798995-f74f-4257-9210-7357dc3b73c9.png)

## 🕵️ Expected behavior

I think an Update button should be provided to the user.

## 🖥 System Info

---

**Comment by collinss-jpl** [comment]
@tloubrieu-jpl This is correct, "findable" is the DataCite equivalent of OSTI"s "released"

**Comment by tloubrieu-jpl** [comment]
Ok, then I will create another ticket for the status enum cleaning.
